### ISSUE TITLE
Large arena size cause server to create invalid scanReply message.

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#10]
**Describe the bug**
The netbots_ipc protocol only supports max distance in a scanReply message of 1415. However the server allows large arena sizes to be created and the server scanRequest message handler does not limit the max distance returned by a scan.

**To Reproduce**
Start the server with a large arena size:
```
py -3 src/netbots_server.py -arenasize 5000 -p 20000 -stepsec 0.05 -games 10 -stepmax 3000
```
Then wait for a robot to scan another robot that is over 1415 distance away.

**Expected behavior**
Needs to be discussed. It is reasonable that scanning should have a max range or should scanning to infinity be possible? The netbots_ipc protocol needs a limit that makes technical sense for messagePack serialization however this may be a very large number, such as any float but not a double.

**Console Output**
From server:
```
ERROR 2019-04-25 21:47:33.709 netbots_ipc.isValidMsg(): Msg 'distance' key has a value 2261.73909721222 which is out of range [0,1415] : {'type': 'scanReply', 'distance': 2261.73909721222, 'msgID': 25391}
ERROR 2019-04-25 21:47:33.710 __main__.recvReplyMsgs(): Could not send because msg is not valid format.
```

**Work Around**
Do not set -arenasize to greater than 1000.

**Comment by dbakewel** [comment]
Related to this issue, should there be a max arena size the server will support? Knowing this may impact the solution to this issue. Please comment below.

**Comment by dbakewel** [comment]
@mcstoer, what do you think? Do you have an idea of what the behavior should be and how to fix it? If so, please respond in the comments below before you do anything. Let's agree on what we are going to do before any code gets written.

**Comment by mcstoer** [comment]
I think it would be interesting to have a max scan range for bots.  In larger arenas this would allow bots to hide or run away while forcing more aggressive bots move around and hunt them.

**Comment by dbakewel** [comment]
OK, if we want a max scan range then it's a bit more work than allowing scanning to infinity. Here is a proposal:

1) To start with we need to deal with max arena size which does have a limit but is not clearly stated anywhere. The protocol (netbots_ipc) already limits effective arena size to 32767 since the robot max x and y location values are 32767. We need to limit this in netbots_server.py on the server command line arguments (argparse). I think we can just add something to the -arenasize line like: choices=range(100, 32767 ), metavar="[100-32767]".

2) To change the max scan value that can be returned, update **scanReply message** definition in netbots_ipc.py to allow distance to field to be larger. I don't see any harm in this being big so lets use **32767** again.

3) Add a new variable to the server conf, let's call it: **scanMaxDistance**. What should the default value be? Perhaps the old max value is a good number to keep for this. It's the hypotenuses of a 1000 by 1000 right angle triangle: **1415**. This default value would not affect any robots that have already been written to run in a 1000x1000 arena. Keeping the old default game mechanics is important.

4) Add server command line support to change scanMaxDistance. Use -scanmaxdistance or -scanmaxdis. 

5) Enforce scanMaxDistance in the server message handler for scanRequests: netbots_srvmsghl.py:scanRequest(). I propose that if a robot is beyond scanMaxDistance then we return 0, same as if no robot has been detected.

6) Finally, most of the items above impact the README.md. Let's of small changes but then there will need to be text added to describe the new game mechanics of scanning in a larger areas as well.

@mcstoer, what do you think? Does that make sense? If you are OK with that then feel free to start working on it. I'm sure it will take a bit of back and forth with pull requests to get it perfect.

**Comment by mcstoer** [comment]
Seems sensible, I won't be working on it for a bit as I am rather busy with my own robot.

**Comment by dbakewel** [comment]
Working on your robot comes first for sure. Well talk on Wed because I'd like everyone to do something like this over the next month. I have a bunch more ideas to add as well. You may find singing more interesting to work on. No rush.

**Comment by mcstoer** [comment]
I would be able to work on this now.

**Comment by dbakewel** [comment]
@mcstoer, if you want to work on this then please do.

**Comment by mcstoer** [comment]
When implementing enforcement for arenasize, when the choice is outside the range the whole range is printed.

`usage: netbots_server.py [-h] [-ip Server_IP] [-p Server_Port]
                         [-name Server_Name] [-games int] [-bots int]
                         [-stepsec sec] [-stepmax int] [-droprate int]
                         [-msgperstep int] [-arenasize [100-32767]]
                         [-botradius int] [-explradius int] [-botmaxspeed int]
                         [-botaccrate float] [-shellspeed int]
                         [-hitdamage int] [-expldamage int] [-obstacles int]
                         [-obstacleradius int] [-jamzones int] [-startperms]
                         [-noviewers] [-debug] [-verbose]
netbots_server.py: error: argument -arenasize: invalid choice: 3 (choose from 100, 101, 102, 103, 104, 105, ... 32759, 32760, 32761, 32762, 32763, 32764, 32765, 32766)`

I replaced the majority of the range with ... to fit it on the page.

**Comment by dbakewel** [comment]
This may help. I haven't tried it myself but perhaps it's a metavar issue.

https://stackoverflow.com/questions/25295487/python-argparse-value-range-help-message-appearance

**Comment by mcstoer** [comment]
I tried this, but it only works for checking the arena size.

```
def arenacheck():
    class RangeCheck(argparse.Action):
        def __call__(self, parser, namespace, values, option_string=None):
            if values < 100 or values > 32726:
                msg = "Invalid choice " + str(values) + " from 100-32726"
                raise argparse.ArgumentError(self, msg)

    return RangeCheck
```

```
parser.add_argument('-arenasize', metavar='100-32767', dest='arenaSize', type=int, action=arenacheck(),
                        default=1000, help='Size of arena.')
```

returns this
```
usage: netbots_server.py [-h] [-ip Server_IP] [-p Server_Port]
                         [-name Server_Name] [-games int] [-bots int]
                         [-stepsec sec] [-stepmax int] [-droprate int]
                         [-msgperstep int] [-arenasize 100-32767]
                         [-botradius int] [-explradius int] [-botmaxspeed int]
                         [-botaccrate float] [-shellspeed int]
                         [-hitdamage int] [-expldamage int] [-obstacles int]
                         [-obstacleradius int] [-jamzones int] [-startperms]
                         [-noviewers] [-scanmaxdistance int] [-debug]
                         [-verbose]
netbots_server.py: error: argument -arenasize: Invalid choice 5 from 100-32726
```

**Comment by dbakewel** [comment]
this seems to work. I added Range exactly as on stackoverflow. Then created new argparse entry at bottom.

```
def quit(signal=None, frame=None):
    log("Quiting", "INFO")
    exit()

class Range(argparse.Action):
    def __init__(self, min=None, max=None, *args, **kwargs):
        self.min = min
        self.max = max
        kwargs["metavar"] = "[%d-%d]" % (self.min, self.max)
        super(Range, self).__init__(*args, **kwargs)

    def __call__(self, parser, namespace, value, option_string=None):
        if not (self.min <= value <= self.max):
            msg = 'invalid choice: %r (choose from [%d-%d])' % \
                (value, self.min, self.max)
            raise argparse.ArgumentError(self, msg)
        setattr(namespace, self.dest, value)

def main():
    d = SrvData()

    random.seed()

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-ip', metavar='Server_IP', dest='serverIP', type=nbipc.argParseCheckIPFormat,
                        default='127.0.0.1', help='My IP Address')
    parser.add_argument('-p', metavar='Server_Port', dest='serverPort', type=int,
                        default=20000, help='My port number')
    parser.add_argument('-name', metavar='Server_Name', dest='serverName', type=str,
                        default="Netbots Server", help='Name displayed by connected viewers.')
    parser.add_argument('-games', metavar='int', dest='gamesToPlay', type=int,
                        default=10, help='Games server will play before quiting.')
    parser.add_argument('-bots', metavar='int', dest='botsInGame', type=int,
                        default=4, help='Number of bots required to join before game can start.')
    parser.add_argument('-stepsec', metavar='sec', dest='stepSec', type=float,
                        default=0.05, help='How many seconds between server steps.')
    parser.add_argument('-stepmax', metavar='int', dest='stepMax', type=int,
                        default=1000, help='Max steps in one game.')
    parser.add_argument('-droprate', metavar='int', dest='dropRate', type=int,
                        default=11, help='Drop over nth message, best to use primes. 0 == no drop.')
    parser.add_argument('-msgperstep', metavar='int', dest='botMsgsPerStep', type=int,
                        default=4, help='Number of msgs from a bot that server will respond to each step.')
    #parser.add_argument('-arenasize', choices=range(100, 32767), metavar='100-32767', dest='arenaSize', type=int,
    #                    default=1000, help='Size of arena.')
    parser.add_argument('-arenasize', dest='arenaSize', type=int, min=1000, max=32767, action=Range,
                        default=1000, help='Size of arena.')
```

**Comment by mcstoer** [comment]
Is it fine to submit the changes with the advanced collisions and classes due to rewriting of sections of the readme?

**Comment by dbakewel** [comment]
Sure, it's a bit of a mess right now anyway. Theres going to have to be some clean up for the next release

**Comment by dbakewel** [comment]
fixed in https://github.com/dbakewel/netbots/commit/a2c0e1b51b1ec9011c0591e4a73c2182d4616130
