### ISSUE TITLE
Binary Search Not Working

### ISSUE THREAD

**Issue by ByonicTao** [dbakewel/netbots#103]
So I'm trying to get binary search to work on a bot, but when it plays any games it just kinda freaks out and scans over and over before shooting off in a random direction. Here's the code I'm using. I think it has something to do with how python handles floats as its always shooting on the same angles of pi.
```
def binaryScan(startRad, endRad, count, distance):
    if count > 5:
        output = {'angle':startRad, 'distance':distance}
        return output

    count += 1
    first = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': startRad, 'endRadians': endRad / 2})
    second = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': endRad / 2, 'endRadians': endRad})

    if (first['distance'] > 0 and second['distance'] > 0 and first['distance'] < second['distance']) or (first['distance'] > 0 and second['distance'] == 0):
        return binaryScan(startRad, endRad / 2, count, first['distance'])
    elif (second['distance'] > 0 and first['distance'] > 0 and second['distance'] < first['distance']) or (first['distance'] == 0 and second['distance'] > 0):
        return binaryScan(endRad / 2, endRad, count, second['distance'])
    else:
        return "ERROR"
```

**Comment by dbakewel** [comment]
OK, so to start with I see that returning "ERROR" means first['distance'] ==0 and second['distance'] == 0. I'm going assume that your code that first called binaryScan handles that case and does not fire at nothing.

Second, you may want to turn on debug output and see the packets going between your code and server (add -debug to your robots command line options). You could also just log the values in the code above before calling scan and then log the result. This will ensure you are sending sane values and getting a good response.

Finally I do see one significant issue in what you do when you say:
```
endRad / 2
```
Let's run your code by hand here and assume that binaryScan was just called as:
```
binaryScan(3.14, 4.7, 2, 8) # the last two numbers don't matter for this example.
```
So this means the first scan should be from 3.14 to half between 3.14 and 4.7. Halfway between 3.14 and 4.7 is 3.92. Let's see what your code does:
```
first = botSocket.sendRecvMessage({'type': 'scanRequest', 'startRadians': startRad, 'endRadians': endRad / 2})
```
startRadians is 3.14 which is good, no change there.
endRadians = endRad /2 = 4.7 / 2 = 2.35 (HMMM...THAT DOES NOT LOOK CORRECT)

So everywhere you have "endRad / 2" you need to update your math. In the example above you want to get to 3.92 so something like:
```
endRadians = starRad + "half distance between StartRad and EndRad" = 3.14 + (4.7 - 3.14)/2 = 3.92
```
For your second scan the math just above is for your startRadians. I think your logic is good besides this one math issue.

Let me know how it goes and this helps or if you have more questions.

**Comment by ByonicTao** [comment]
Thanks, got it working now. It was the math issue along with a similar one in my firing code.

**Comment by dbakewel** [comment]
Great, happy to hear that!

I had one more thought. Don't forget that the response from a scanRequest can be an error message (https://github.com/dbakewel/netbots#scan). This will happen if you scan while your robot is dead. Your if statement does not cover this case and python with throw an exception if an error message is returned. Hopefully you catch this already in the code that calls binaryScan.
