### ISSUE TITLE
NetBots_Math.project help

### ISSUE THREAD

**Issue by cyrus123live** [dbakewel/netbots#105]
Hey quick question, I was wondering what the exact return type of the method Netbots_Math.project was, as the documentation says that it returns a point. Is this a type of variable? And if so how do I access the x and y components of it?

Thanks!

**Comment by dbakewel** [comment]
The function returns two floating-point numbers. Python allows functions to return more than one thing. This is something you might not be used to coming from C or Java.

Here's an example taken from the server code. You can find more examples by searching the [server](https://github.com/dbakewel/netbots/blob/master/src/netbots_server.py) code in the netbots [src](https://github.com/dbakewel/netbots/tree/master/src) directory. You can also look at the code for the [math](https://github.com/dbakewel/netbots/blob/master/src/netbots_math.py) module to see how this function is able to return more than one value.

```
x, y = nbmath.project(bot['x'], bot['y'],
          bot['currentDirection'],
          bot['currentSpeed'] / 100.0 * d.getClassValue('botMaxSpeed', bot['class']))
```

**Comment by cyrus123live** [comment]
Oh ok thanks!
