### ISSUE TITLE
Shell Speed?

### ISSUE THREAD

**Issue by Origamifish** [dbakewel/netbots#106]
Am I just bad or is there something in the documentation that says how to get the shell speed in a particular game from a bot perspective?

**Comment by mcstoer** [comment]
Should be in SrvData class that is passed to each robot.

**Comment by dbakewel** [comment]
Yes the joinReply message contains a copy of the server conf, which contains the shell speed.

If your robot is based on the demo bots then it has some code like this that gets a joinReply:
```
joinReply = botSocket.sendRecvMessage({'type': 'joinRequest', 'name': robotName}, retries=300, delay=1, delayMultiplier=1)
```
and then code that pulls out the server conf:
```
srvConf = joinReply['conf']
```
From that you can get shell speed using:
```
shellSpeed = srvConf['shellSpeed']
```

You can see everything in the server conf by looking at the [Server Configuration](https://github.com/dbakewel/netbots#server-configuration) in the README.

**Comment by Origamifish** [comment]
ty
