### ISSUE TITLE
What is it that each robot level does?

### ISSUE THREAD

**Issue by raineyfu** [dbakewel/netbots#107]
What is it that each robot level does that make it stronger than the last?

For example, robot level 1 uses a binary search, robot level 2 "rescans the last slice it fired at to see if target is still there and then progressively opens up scan area to reacquire enemy", and robot level 3 "moves when it detects that health is being reduced". 

What are the improvements made to robot levels 4, 5, 6, 7, and 8 that make them stronger than the previous iteration?

**Comment by mcstoer** [comment]
From what I remember, level 7 and level 8 use the same logic in what messages are being sent, but level 8 sends messages asynchronously.

**Comment by dbakewel** [comment]
Check this new video out, what you want starts at about 8:00: https://youtu.be/X7AE1N0ve0Y

The video also has the results from the weekend and a deeper look at how to use stats to improve your robot.
