### ISSUE TITLE
Gathering other Bots Data

### ISSUE THREAD

**Issue by MatthewHightech** [dbakewel/netbots#108]
Hello there :) 

I was wondering if there's a nb function that returns data from other bots. For example; health, shots fired, points, etc. 

Thanks!
- Matt Smith

**Comment by dbakewel** [comment]
I'm afraid not. That information is deliberately hidden as part of the game mechanics. The question is: what can you guess about the other robots based on the information you do have?

**Comment by MatthewHightech** [comment]
Okay, thanks! I'll definitely think about that and see if I can use anything to my advangage 😄
