### ISSUE TITLE
Removing getInfoRequest

### ISSUE THREAD

**Issue by ByonicTao** [dbakewel/netbots#109]
So I'm trying to remove the get info request message from my bot, which was built on the skeleton of the demo bots. But when I remove the 
`try:
            # Get information to determine if bot is alive (health > 0) and if a new game has started.
            getInfoReply = botSocket.sendRecvMessage({'type': 'getInfoRequest'})
        except nbipc.NetBotSocketException as e:
            # We are always allowed to make getInfoRequests, even if our health == 0. Something serious has gone wrong.
            log(str(e), "FAILURE")
            log("Is netbot server still running?")
            quit()`
the script quits after one game. What can I do to keep the functionality of checking if I'm dead but also removing getInfoRequest? 

Also how is speed calculated? Is it units/step?

**Comment by dbakewel** [comment]
I use a main loop like the one below and don't have any inner loops. It is still based on the demo robot, but it never checks if the robot is alive while playing a game. It just assumes we are still playing unless a message exception is raised then it waits until health > 0 again. 

It never uses getInfoRequest while playing, only while waiting. This also means it is very possible that the robot will not know a new game has started when it is one of the last two robots in the game. When the last robot dies, the new game starts immediately and the winner and last robot to die will not see any message errors. Your robot needs to be OK with not detecting new games.

This is only one way to do this. There are any others and some ways will be better depending on what you are doing.

```
def play(botSocket, srvConf):
    mode = "wait"
    while True:
        if mode == "wait":
            try:
                getInfoReply = botSocket.sendRecvMessage({'type': 'getInfoRequest'})
                if getInfoReply['health'] != 0:
                    # We are alive, start playing!!!
                    mode = "play"
                    # Set up for new game here BUT this code will not always run because we will
                    # not always detect new games.
            except nbipc.NetBotSocketException as e:
                #We are always allowed to make getInfoRequests, even if our health == 0. Something serious has gone wrong.
                log(str(e),"FAILURE") 
        else:
            try:
                ### THIS IS WHERE THE PLAYING CODE GOES.
                ### THIS CODE NEVER SENDS getInfoRequest. 
            except nbipc.NetBotSocketException as e:
                #Assume our health is 0. Wait for our health to increase above 0.
                mode="wait"
                ### Don't bother logging this exception, we expect it to happen.

```

I then mix the code above with my binary search similar to [this code](https://github.com/dbakewel/netbots/issues/104#issuecomment-639739031). My code only uses the top whiel loop for all lopping. If you put all that together then you can see one way to code this.

Yes, speed is given in units/step. Max speed is available in the server conf message returned in the join reply. See [shell speed](https://github.com/dbakewel/netbots/issues/106#issuecomment-640295949) for more info about server conf.

**Comment by ByonicTao** [comment]
Thanks, I came up with the same solution after a couple hours of just playing around with it 😄. Good to know that it's valid.
