### ISSUE TITLE
How do scans/distance work with only seeing part of a robot?

### ISSUE THREAD

**Issue by Ryast89** [dbakewel/netbots#112]
If a robot's scan sees part of a robot that does not include the center, will it still return a distance that isn't zero? If it does, what is that distance the robot gets?

Alternate question, if it does see the bot, is there any way to focus on the center of a robot to get more precise shots?

**Comment by dbakewel** [comment]
Thanks for the question @Ryast89. I looked at the server code and the center of the robot must be inside the scan for the robot to be returned. So if a scan only sees the side of the robot, not including the center, then that robot is not visible to the scan.
