### ISSUE TITLE
Bot is occasionally firing twice in two steps

### ISSUE THREAD

**Issue by Ryast89** [dbakewel/netbots#114]
I changed my bot so that it uses a timer instead of checking for an existing shell before firing. I'm using method 3 that you suggested in the issue on alternatives for step tracking.

After switching to this system, I started noticing issues where a bot will fire a shell, then fire a shell on the step immediately after that one (incrementing the cannons fired stat twice). This second shell seems to happen because of the same fire request as the first one, because I added a log after each fire request to tell me a shot was fired and I'm only seeing it once. I went back to some of my older bots, and I'm seeing the issue with those bots as well.

Is this an issue that only I'm having, or is this a universal mechanic/bug?

**Comment by dbakewel** [comment]
I think you are seeing the reality of an unreliable network. Assuming your code is good then this is probably related to dropped packets. You can test if this by adding "-droprate 0" to the server's command line. This will turn off dropped packets. 

This is what may be happening: 
1. Your robot sends a "fireCanonRequest" using netbots_ipc.sendRecvMessage()
2. The server gets the message and fires the cannon and the server sends back a fireCanonReply message.
3. The fireCanonReply message is dropped so your robot never gets it.
4. After one step has gone by netbots_ipc.sendRecvMessage() realizes that it never got a fireCanonReply so it resends the original fireCanonRequest. See [sendRecMessage](https://github.com/dbakewel/netbots#sendrecvmessagemsg-destinationipnone-destinationportnone-retries10-delaynone-delaymultiplier12) for details.
5. The server gets the message again and fires the cannon again then the server sends a fireCanonReply message back again.
6. Assuming this fireCanonReply gets to your robot this time, your original call to netbots_ipc.sendRecvMessage() will return success.
This is one example that would explain what you are seeing. Unreliable networks are trickly.

Please try the "-droprate 0" server option and let me know if the problem goes away.

**Comment by Ryast89** [comment]
Pretty sure you're right on the solution. Didn't realize the sendrecv message would send again if it didn't get a response, but it makes sense. Thanks!
