### ISSUE TITLE
Viewer Instant Replay

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#17]
**Is your feature request related to a problem? Please describe.**
When -stepsec is on a fast setting it is very hard to see what in happening in the viewer.

**Describe the solution you'd like**
Add a button to the viewer that replays the last 10 secs at the default -stepsec. After the replay it jumps back to the live feed at the -stepsec of the game.

**Describe alternatives you've considered**
Lots of options. **Discuss in the comments**

**Additional context**

**Comment by dbakewel** [comment]
@jtaevans is assigned. Please write in implementation proposal.

**Comment by jtaevans** [comment]
A key listener will be implemented.
When the space bar is pressed, the replay will begin in `checkForUpdates()`.

The `msg` dict from the last 300 steps or so will be stored in the list `replayData`.

When the instant replay is activated, the `msg` that was received from the server will be replaced by the first item of `replayData` before graphics drawing is conducted. That first item will then be removed from the list. This will continue every iteration of `checkForUpdates()` until `replayData` is empty. At that point, the `msg` received from the server will no longer be replaced, and therefore the viewer will begin drawing live data again.

A simplistic implementation of this plan has been successfully attempted.

**Comment by dbakewel** [comment]
Ok, go for it. That "might" work. Please do some reading on what python list type is best to implement replayData. Probably just the normal list [] type. Get it working and we can tune for performance after and code format etc.

One other question. What happens if I press spacebar during reply? Start reply again? Go back to live?

**Comment by jtaevans** [comment]
Yes, I already have it working with the normal list [] type. 

I think that if the spacebar is pressed during replay it would be most logical to go back to live.

**Comment by dbakewel** [comment]
Yup, going back to live seems fairly logical.

**Comment by dbakewel** [comment]
@jtaevans  please make sure you fork is up to date before you update the code and submit a pull request. Otherwise conflicts are likely to occur.

**Comment by dbakewel** [comment]
This seems to work well. Thanks @jtaevans
