### ISSUE TITLE
Improve Shells in Viewer

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#18]
**Is your feature request related to a problem? Please describe.**
The view is just a bunch a circles. Let's make shells look a little nicer.

**Describe the solution you'd like**
Make shells into small arrows.

**Describe alternatives you've considered**
Lots of options. **Discuss in the comments**

**Additional context**

**Comment by mcstoer** [comment]
Instead of making the shells into small arrows, make the shells into small line segments.

**Comment by dbakewel** [comment]
Yes, lines or arrows. Anything would be better than the current circles.

**Comment by dbakewel** [comment]
@MCSnapTurtle please propose a full concept.

**Comment by MCSnapTurtle** [comment]
I will try to make the shells into line segments first, as that is easiest.

**Comment by dbakewel** [comment]
OK, sounds good. Incremental improvements is the way to go.

**Comment by MCSnapTurtle** [comment]
I have a question when I modify the coordinates of the shell, it does nothing, and shells are the exact same size. When I modify the "scale" it also doesn't do anything either. All I can do is change the shape to a square. Any idea why?

**Comment by dbakewel** [comment]
Nope, I think I'll need to see the code. Please put code in comment or put in a  pull request. If you put code in a comment please do it like this:
```
codes dlfsld flad fl
code sdlfksjfls 
```

See the following for git hub formatting: https://github.github.com/gfm/

**Comment by MCSnapTurtle** [comment]
Classmates helped me troubleshoot, and now the code works. I have functioning "missile shaped" shells. These are a line with a triangle at back end of it. Everyone likes them, should I make a pull request?

**Comment by dbakewel** [comment]
Yes please!
