### ISSUE TITLE
Robot Colors in Viewer

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#19]
**Is your feature request related to a problem? Please describe.**
The colors of robots in the viewer are ugly and only 8 robots are supported.

**Describe the solution you'd like**
Choose more colors (up to 32?). Make sure the first 8 colors all look good and are easy to tell apart. **Discuss in comments**

**Describe alternatives you've considered**
none

**Additional context**
[tk colors](https://www.tcl.tk/man/tcl/TkCmd/colors.htm) reference. Any hex color can also be used.

**Comment by JamesDarby345** [comment]
I made a pull request with 10 colours that are all good and easy to tell apart, they are based on the Super Smash Bros Ultimate player colours. I used Hex codes,

**Comment by dbakewel** [comment]
Proposed pull request is https://github.com/dbakewel/netbots/pull/41
