### ISSUE TITLE
Different types of collisions cause different damage.

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#22]
**Is your feature request related to a problem? Please describe.**
It seems odd that robots take the same damage regardless of the details of a collision. Should a head on collision between two robots really cause the same damage as one robot being still? What about collisions with walls? It's nice that the game mechanics are simple right now but there is not much benefit for robots that avoid collisions. 

*The goal with this work would be to give a real advantage to robots that work to avoid collisions.*

**Describe the solution you'd like**
Not sure. Open to ideas. **Please discuss in the comments.**

**Describe alternatives you've considered**
In a simple form, at least different damage for colliding with walls, obstacles, and other robots. Walls and obstacles are easy to avoid so they should reduce health by more. Robot/Robot collisions are harder to avoid so could cause less damage. That would be one simple approach.

**Additional context**
Right now, the demo robot wallbanger does fairly well even through it rams into walls. It seems like train, which moves slower, should do better since it is working harder to avoid damage.

**Comment by mcstoer** [comment]
**Damaged based on the Magnitude of the Bots' Velocities**
Damage should be based on the portion of the colliding objects' velocities parallel to the direction of contact.  This can be done by finding v₁cosθ₁ + v₂cosθ₂ for bots one and two.  θ is the angle between the velocity and the direction of contact.  The direction of contact is direction from the center of a bot to the point of contact with another bot.  This could also be applied to wall collisions.

**Comment by dbakewel** [comment]
@mcstoer that is a good idea. So a robot trying to run along a wall and bumping it would take less damage than a dumber robot that rams strait into it. That is a good real world approach. Also a robot that tries to turn out of the way of another robot but just barley hits takes less damage than not trying at all. In both cases a robot gets a benefit by being smarter. All this would apply to obstacles as well.

**Comment by dbakewel** [comment]
@mcstoer please provide a full proposal of the new game mechanics.

**Comment by dbakewel** [comment]
@mcstoer do you still want to work on this or would you rather work on https://github.com/dbakewel/netbots/issues/46 ?

**Comment by mcstoer** [comment]
@dbakewel I'm still planning to work on it, #46 was just an idea I wanted people to develop.

**Comment by mcstoer** [comment]
**New Collision Damage**
When two objects collide, they take up to a maximum of 10 damage depending on both of their directions and speeds.  This will be calculated by finding the speed which is going towards the collision point ( v₁cosθ₁ + v₂cosθ₂ ).

b['hitDamage'] can be changed to hold the amount of damage each bot will take.
The calculation can be done under  _while: foundOverlap:_ so the positions at collisions will be moved.
Bots heading away from a bot colliding with them will take reduced damage since their speed component heading towards the other bot is negative.

The readme will need to be updated to reflect these changes.

**Comment by dbakewel** [comment]
OK that sounds reasonable. A few notes:

- I assume when you say two "objects", you mean robot, obstacle , or wall.

- The "maximum of 10 damage" should be a in the server conf and be changeable by using a server commend line option. 

- Is there an option to keep the old behavior? I'm not too concerned about this but if it's easy then please do it.

- Keep in mind that all the logic to find overlaps may run multiple times. This is because moving robots to deal with the original collision may result is secondary collisions. The spacing of walls, obstacles, and robot start locations have enough space around them to ensure this loop will always resolve but it may run more than one. **I think the damage should only be inured from the original collision, not secondary collisions caused by the loop. Does that make sense?**

- If possible put the math you need in a new function(s) in the netbots_math module. Only do this if the math is general enough that it might have some future use to someone else. Conversely, please don't implement new math if functions already in the netbots_math module can be used.

Looks cool. Looking forward to it.

**Comment by dbakewel** [comment]
Hey @mcstoer I had to remove the test viewer and robot to merge into orgin. I tried to put them back on your branch but I lost access to it after the pull request was complete. Sorry. If you need then, you can recover them from a previous commit. I'm happy to help with that if needed.

**Comment by dbakewel** [comment]
Implemented in https://github.com/dbakewel/netbots/commit/2c9114132ee47f5e290e00b277726e7029bc7e99
