### ISSUE TITLE
Clients fail to connect if server has not started yet.

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#23]
**Describe the bug**
Anytime one script is used to start the server and clients (robots and viewer) there is a race condition. The clients will only wait so long for the server to start listening and responding to joinRequest and addViewerRequest messages. If the server is slow to start then clients can time out and quit. 

**To Reproduce**
The is issue is hard to reproduce but on a slow computer run the rundemo.bat script. Since the server has more work to do before opening it's socket there will be a chance that clients will time out and quite before the server can respond to them.

The problem can also be seen if the server is not started first. For example, if the viewer is started it will not wait for the server to start.

**Expected behavior**
The clients should retry for longer (10 seconds default) before they quit. This should probably be a comment line option for the number of seconds to keep trying to connect to server. A setting of 0 should mean keep trying forever.

**Console Output**
```
D:\netbots\robots>py -3 hideincorner.py
INFO 2019-04-30 20:49:56.988 netbots_log.setLogLevel(): DEBUG logging = False. VERBOSE logging = False
INFO 2019-04-30 20:49:56.990 netbots_ipc.__init__(): Source Socket Binding Successful. Listening on 127.0.0.1:20010
INFO 2019-04-30 20:49:59.589 __main__.main(): Is netbot server running at127.0.0.1:20000?
FAILURE 2019-04-30 20:49:59.590 __main__.main(): Failed to get valid respose.
INFO 2019-04-30 20:49:59.591 __main__.quit():

                 ====== Stats ======

               Messages Sent: 10
              Messages Recv: 0
     sendRecvMessage Calls: 1
   sendRecvMessage Resends: 10
  Avg sendRecvMessage Time: 0.000000 secs.

                Messages Sent by Type
               joinRequest: 10

                Messages Recv by Type


INFO 2019-04-30 20:49:59.592 __main__.quit(): Quiting
```

**Work Around**
Add a delay to the rundemo.bat script after the server start line and before and of the client start lines.

**Comment by mcstoer** [comment]
This bug is easier to produce by setting the stepsec value to 1 or even larger numbers.

**Comment by dbakewel** [comment]
Suggested fix 

Change the join lines in robots and viewer to retry every second for 5 minutes: retries=300, delay=1, delayMultiplier=1

**In robots:**
```
botSocket.sendRecvMessage({'type': 'joinRequest', 'name': robotName})
```
can become:
```
botSocket.sendRecvMessage({'type': 'joinRequest', 'name': robotName}, retries=300, delay=1, delayMultiplier=1)
```

**In viewer:**
```
d.viewerSocket.sendRecvMessage({'type': 'addViewerRequest'})
```
can become:
```
d.viewerSocket.sendRecvMessage({'type': 'addViewerRequest'}, retries=60, delay=1, delayMultiplier=1)
```

**Comment by mcstoer** [comment]
This solution works quite well.

**Comment by dbakewel** [comment]
@lsh010815 please put in a pull request for this.

**Comment by dbakewel** [comment]
Fixed in https://github.com/dbakewel/netbots/pull/51
