### ISSUE TITLE
Let the robot gains some points when it killed another robot

### ISSUE THREAD

**Issue by lsh010815** [dbakewel/netbots#27]
**Is your feature request related to a problem? Please describe.**
Some time the robot died too fast in one game, because all three other robots are shooting at it. The robot has to get more points next game to catch up. However, ten points are not enough for many situations.

**Describe the solution you'd like**
When a robot kills another robot, it will gain 1 or 2 points. Also, add how many this robot killed in game board.

**Describe alternatives you've considered**
Let the robots can get more than 10 points in one game, to make the game more stimulating and fair.

**Comment by dbakewel** [comment]
Hmmm...OK I'm thinking about this from a game mechanics and fairness perspective. If a robot gets points for killing another robot then I feel it should have taken some specific action to get those points. In other words it has to be something besides luck. Here are some thoughts:

1) A robot does not know the health of the enemy robot so it cannot know that firing at it will kill it. So a robot cannot plan to get points for firing the kill shot.

2) Following from 1), a robot may do 90% of the damage to an enemy robot but another robot may get the kill shot. Is it fair that the robot that gets the kill shot should get the points? 

3) Currently robots that inflict the most damage tend to get get the most points. Also, robots that inflict the most damage tend to get more kill shots. Therefore robots that get more kill shots already tend to get more points. So in a round about way the proposed game mechanic is already built in.

This is only my point of view. Others please let me know what you think.

**Comment by dbakewel** [comment]
I guess another way to ask my questions above is simply: Can you explain how to write a robot to take advantage of this feature?

**Comment by lsh010815** [comment]
![image](https://user-images.githubusercontent.com/49734269/57173201-f27eaa00-6de0-11e9-8d41-55d96012426d.png)

So here you can see my robot has almost 3000 damage ahead of second lighthouse robot, but it is still losing to the light blue one. Also, you can see these three totally same lighthouse robots have close damage, but the points between them are quite large.

**Comment by lsh010815** [comment]
The robot which does the most damage cannot get the highest points, it seems to be unfair for this robot. For example, if your robot just do nothing but just hide behind other robots, it can always get second place which will give you 5 points. When you are facing three nearly strong robots, you can get 15 points for three game, but other three robot can only get 0+2+10 which are 12 points ideally. So the your robot will always win the game. If killing other robots will give points, it only encourage the robots to fight against each other, it also can makes the game more exciting.

**Comment by dbakewel** [comment]
For the tournament above, can you rerun it with a thousand games and post the full server stats and scoreboard after game 1000 please. With those robots we may need to run more games to really get rid of luck.
