### ISSUE TITLE
Graphical indication of current scan direction, and movement direction

### ISSUE THREAD

**Issue by JamesDarby345** [dbakewel/netbots#28]
**Is your feature request related to a problem? Please describe.**
Having graphical indications of where the robot is currently scanning, by having a gun barrel, could be just a rectangle, point down the middle of the current scan area would help make the game more watchable and easier to understand what the robots are doing for debugging purposes or for trying to improve your robot. The same idea can be applied to where the robot is moving by changing what the robot looks like by adding something that indicates it's current direction, whether that is simply an arrow on the circle or changing how the robots look entirely. Such as making them look like a tank etc.

**Describe the solution you'd like**
Adding a graphical element to the viewer that indicates where the robot is scanning and moving.

**Describe alternatives you've considered**

**Additional context**

**Comment by dbakewel** [comment]
OK, sounds interesting. It should have an off/on switch on the server so the server knows not to send that data to the viewer. That way tournaments where players don't want to expose their robots behavior can be run. The default would be off so it keeps the current behavior by default.

Can you draw an example and paste it into a comment?

What do others think of this? Do you want other to see what your robots are doing?

**Comment by dbakewel** [comment]
Also, please look at https://github.com/dbakewel/netbots/issues/24. Do these conflict?

**Comment by JamesDarby345** [comment]
![image](https://user-images.githubusercontent.com/49734270/57656673-f3a49980-758d-11e9-9c53-3ad0a8e0de90.png)
It could look something like that, very much like some sort of tank like that though, which is essentially how the netbots are behaving right now. This could be implemented just by drawing more geometric objects. Excuse the extra dot and cursor, I am so bad at paint I use blender to make a 2d drawing instead.

**Comment by MCSnapTurtle** [comment]
@JamesDarby345 As we were using ship names, so why don't we make the bots look more like ships? Will post example soon.

**Comment by MCSnapTurtle** [comment]
![ship](https://user-images.githubusercontent.com/49734276/57657493-57c85d00-7590-11e9-8fff-f4be70dd75b6.png)

**Comment by dbakewel** [comment]
OK, I like the little tank idea. I feel like the tank is still round enough that it will visually look circle like. Since the server will still treat the robot as a circle we don't want to get to far from that. All non circle parts will overlap walls etc which will look odd.

**BEFORE** you do anything. Please work out with between @JamesDarby345 and @mcstoer if this conflicts with https://github.com/dbakewel/netbots/issues/24? Should https://github.com/dbakewel/netbots/issues/24 be done instead? Should https://github.com/dbakewel/netbots/issues/24 be closed? Should both of them be done?

@JamesDarby345, once you work out what's to be done with https://github.com/dbakewel/netbots/issues/24 feel free to submit a pull request with a sample implementation. I'm sure it will take a bit of back and forth with the code since TK is a pain.

I would like to see an implementation of **just the direction indication first**. The server does not currently send any information to the viewer about scan direction so that's a much bigger change. Adding direction indication is a change to the viewer only.

**Comment by dbakewel** [comment]
Keep in mind future expansion so each robot class could look different. They can all look the same for now. See https://github.com/dbakewel/netbots/issues/39 for more information.

**Comment by dbakewel** [comment]
Also, I was thinking that showing the scan direction is nice but it would be more interesting to show the last scan range. The image below is not great but you'll get the idea. 

![image](https://user-images.githubusercontent.com/11411338/57729050-1c8a6480-764a-11e9-9613-ecf365a7fde2.png)

**Comment by mcstoer** [comment]
Our current movement system is much closer to a 4 wheel steering vehicle.  I suggest adding a robot that keeps the circular collision but allows for future customization.  This can be done by creating a circular bumper around the vehicle, as shown in the drawing below.  The customization element can also complement #39 as you could draw what your specialized vehicle looks like.
![BotDesign](https://user-images.githubusercontent.com/49734282/57740379-73089a80-766c-11e9-938b-68ea844309b1.png)

**Comment by jtaevans** [comment]
The movement system is quite similar to that of a helicopter. The rotor could visually represent the circular collision bubble. 


![helicopter](https://user-images.githubusercontent.com/49734285/58283822-2e60bb80-7d5e-11e9-9271-74b77f660dd6.png)

**Comment by mcstoer** [comment]
I quite like this new robot design, here is a sketch I drew:
![copter](https://user-images.githubusercontent.com/49734282/58284561-bbf0db00-7d5f-11e9-8148-c29f36a3b6a9.png)

**Comment by dbakewel** [comment]
See comments added to pull request: https://github.com/dbakewel/netbots/pull/74

**Comment by dbakewel** [comment]
**Data for last direction fired and last scan.**

I've updated the head of the development branch with https://github.com/dbakewel/netbots/commit/728fe877767a4426e9e1bb832cc1a0368a71e893 .

This provides data to the viewer for the last fireCanonRequest and last scanRequest from each robot. The data should be available in the viewer with code below (untested):

```
            bot['last']['fireCanonRequest']['direction']
            bot['last']['fireCanonRequest']['distance']
            bot['last']['scanRequest']['startRadians']
            bot['last']['scanRequest']['endRadians']
```

**Comment by dbakewel** [comment]
See the head of https://github.com/dbakewel/netbots/tree/develop for scan indication and requested direction indication in viewer. What do you think? Code changes are in https://github.com/dbakewel/netbots/commit/118d82e34cf3e804199fa89ce80c21fb4f77d4eb for display and  https://github.com/dbakewel/netbots/commit/728fe877767a4426e9e1bb832cc1a0368a71e893 for data.

What do you think?

**Comment by dbakewel** [comment]
Also see https://github.com/dbakewel/netbots/commit/1c116bd92a10eb89bee67a8558290f9abcd1362d for robot canon added to viewer.
