### ISSUE TITLE
Will the hardware of the computer impact the game?

### ISSUE THREAD

**Issue by lsh010815** [dbakewel/netbots#29]
![image](https://user-images.githubusercontent.com/49734269/57173414-7d14d880-6de4-11e9-9331-ced396486fb9.png)

This picture is when the game is running on school computer. My robot is facing three lighthouse + wallbanger + lock on mode robots, and mine is losing. However, when I run the same situation on my computer, everything changed. (Demo: Wallbanger and Demo: Lighthouse are same robots)

![image](https://user-images.githubusercontent.com/49734269/57173456-0fb57780-6de5-11e9-97e0-774cab6e6eff.png)
![image](https://user-images.githubusercontent.com/49734269/57173470-307dcd00-6de5-11e9-82ee-e475ee428b22.png)

In first image, all of the robots' damage per shot are lower than 3, but on my computer everyone's avg damage is higher than 3, and Tirpitz almost gets 4. Also, Tirpitz is 200 points ahead, but it never happens on school computer. The only difference between these two games is they were running on different computer, so I wonder if the different computers will make the result different.

**Comment by dbakewel** [comment]
What was -stepsec set to? Did you see any warnings in the servers output? Also, please post the entire server stats from the end of the tournament.

**Comment by dbakewel** [comment]
I'll do some of my own testing this weekend as well. I'll post the results in a while.

**Comment by dbakewel** [comment]
I've run some tests on 3 different computers. I have not seen the same issue. All my results have different point totals but the [percent of total points](https://github.com/dbakewel/netbots/issues/31) for each robot is within +/- 1%.  To get this result I had to run 1000 games in each tournament and I had to make sure -stepsec was not too fast.

There may be some others things that can help ensure everthing is fair and the same from one tournament to the next, such as https://github.com/dbakewel/netbots/issues/30.

I will keep this issue open for now and look into it some more.

**Comment by dbakewel** [comment]
Also see this comment: https://github.com/dbakewel/netbots/issues/32#issuecomment-489485938

**Comment by lsh010815** [comment]
I tired to run the program with 1000 games again on my computer, but the robots will suddenly just quit like you described in #23 if I run too many games. However, the result seems to be same like last time. The -stepsec is 0.0025, and the only warning I got from server is Server running slower than 0.0025 sec/step. I still need to wait for tomorrow to run the game on school computer.

**Comment by dbakewel** [comment]
After doing some more testing it looks like any differences +/- 1% of points over 1000 games is normal and based on luck. More than that and -stepsec is to fast. I've done everything I can to take luck out of the equation in **[Fair_Start_Positions](https://github.com/dbakewel/netbots/tree/feature/Fair_Start_Positions)**. This new code also allows much faster -stepsec. See https://github.com/dbakewel/netbots/issues/32#issuecomment-489498700 for details.

With respect to robots quiting. I'm not sure that the problem I'm describing in  https://github.com/dbakewel/netbots/issues/23 could be impacted by the number of games. It's possible you are seeing a different problem.

**Comment by dbakewel** [comment]
I created issue https://github.com/dbakewel/netbots/issues/34 for robots not getting response during a tournament. This is a separate issue from https://github.com/dbakewel/netbots/issues/23 and will need a different solution.

**Comment by lsh010815** [comment]
I also run the game in school computer, but there is the same problem in school computer. Some of the robots just quit when the server start a new game. I need to run the game again tomorrow, and set -stepsec bigger.

**Comment by dbakewel** [comment]
Read the comment I added to issue 34: https://github.com/dbakewel/netbots/issues/34#issuecomment-489766960.

This is probably something you just need to deal with yourself in the robots if you want to do fast testing. We can talk more about this on Wednesday.

**Comment by dbakewel** [comment]
I released the changes into the master branch so you don't need to use the Fair Start Position branch any more. See https://github.com/dbakewel/netbots/blob/master/CHANGELOG.md
