### ISSUE TITLE
Poor server side performance 

### ISSUE THREAD

**Issue by MCSnapTurtle** [dbakewel/netbots#32]
**Describe the bug**
The server is unable to run at a fast speed (ie. 0.01 step/sec) without throwing warnings that the server is running slower than it should be. I think the main thing slowing it down is the messages it receives from the bots?

This slow performance makes testing bots take much longer than it should. 

I'm not sure what is the bottleneck, because the PC is powerful enough to be able to run the game at a fast speed without the server lagging. Is it python or windows itself causing the lag?

**To Reproduce**
Make the step/sec faster, such as 0.01.

**Expected behavior**
 Runs without slowing down.

**Console Output**
"Warning: Server is running slower than x step/sec"

**Work Around**
Running the bots on other PC's allows the game to run at a higher step/sec.
Turning off viewer may help, but often isn't enough to fix it.

**Comment by JamesDarby345** [comment]
I can run it at 0.005 steps/sec with it only saying the server is running slower than that right after it prints the scoreboards, so it may be CPU dependent. 

Edit: It still could be the server failing to handle a lot of messages as my test was with basic robots

Note: this is with 8 bots that don't send too many messages (5 trains, 1 hide in corner, 1 lighthouse, 1 wall banger)

**Comment by MCSnapTurtle** [comment]
Alright, I'll try to do more testing. Thanks for the input.

My bots do spam messages constantly, which may be a problem

**Comment by dbakewel** [comment]
I have an i7-6700K at 4GHz. I can run 4 servers (each with 4 bots connected) at -stepsec 0.0025 (400 steps/sec). However the server only seems to go 288 steps/sec.  I don't see any "Server running slow" warnings. I think the difference between 400 and 288 may be overhead of putting the process to sleep and waking it back up. Also, the loop timer does not account for the overhead of sleeping the sever process.

I am trying a lot of things to ensure the server if fair. You may want to try testing with these changes since they all improve performance and fairness. From github, switch to the [Fair Start Positions](https://github.com/dbakewel/netbots/tree/feature/Fair_Start_Positions) branch. I have not added any of this to the master branch because it's a lot of change and there may be new bugs. Also, I will try and add a better sleep with lower overhead later tonight but it will need to busy wait so that may not work out.

**Comment by dbakewel** [comment]
I've updated the  **[Fair Start Positions](https://github.com/dbakewel/netbots/tree/feature/Fair_Start_Positions)** branch. I removed time.sleep() from the server and replaced it with a busy wait. The server much more accurately times each step but it uses 100% of 1 CPU core to do it. Please download the branch and test. If you see any problems please post the full server output. It now looks like this:

```
INFO 2019-05-05 21:16:33.303 __main__.logScoreBoard():

                ------ Score Board ------
               Tournament Time: 966.120 secs.
                         Games: 1000
             Average Game Time: 0.966 secs.
                         Steps: 480718
          Average Steps / Game: 480.718
                      Run Time: 966.234 secs.
      Time Processing Messages: 145.594 secs.
                   Messages In: 1709364
                  Messages Out: 1424470
              Messages Dropped: 284894
               Messages/Second: 3538.199
         Time Processing Steps: 17.501 secs.
                  Steps/Second: 497.517
                 Time Sleeping: 798.854 secs.
            Average Sleep Time: 0.001662 secs.
     Steps Slower Than stepSec: 1050 (0.22%)

                    ---- Score -----  ------ Wins -------  --------- CanonFired ----------
              Name      Points     %    Count   AvgHealth    Count   AvgDamage   TotDamage  IP:Port
 ------------------------------------------------------------------------------------------------------------------
           Level 7        4871  28.8      337       41.22    24988        4.40   109864.40  127.0.0.1:20004
           Level 6        4577  27.1      312       41.28    23784        3.98    94723.09  127.0.0.1:20003
           Level 5        4267  25.2      226       34.64    26256        3.64    95605.22  127.0.0.1:20002
           Level 4        3203  18.9      116       33.70    19215        3.48    66825.72  127.0.0.1:20001
 ------------------------------------------------------------------------------------------------------------------
```

**Comment by dbakewel** [comment]
I tested at 1000 steps/sec (-stepsec 0.001) and it works well as long as no viewer is attached. The results are very similar (+/- 1% of points %) to the 500 steps/sec run above.

```
INFO 2019-05-05 22:33:09.712 __main__.logScoreBoard():

                ------ Score Board ------
               Tournament Time: 509.020 secs.
                         Games: 1000
             Average Game Time: 0.509 secs.
                         Steps: 503913
          Average Steps / Game: 503.913
                      Run Time: 509.078 secs.
      Time Processing Messages: 150.470 secs.
                   Messages In: 1731955
                  Messages Out: 1443296
              Messages Dropped: 288659
             Messages / Second: 6804.281
         Time Processing Steps: 18.229 secs.
                Steps / Second: 989.967
                 Time Sleeping: 336.002 secs.
            Average Sleep Time: 0.000668 secs.
     Steps Slower Than stepSec: 2161 (0.43%)

                    ---- Score -----  ------ Wins -------  --------- CanonFired ----------
              Name      Points     %    Count   AvgHealth    Count   AvgDamage   TotDamage  IP:Port
 ------------------------------------------------------------------------------------------------------------------
           Level 7        5030  29.8      358       39.51    25548        4.29   109636.01  127.0.0.1:20004
           Level 6        4488  26.6      306       43.70    24202        3.80    91964.81  127.0.0.1:20003
           Level 5        4269  25.3      221       35.58    27095        3.59    97187.77  127.0.0.1:20002
           Level 4        3116  18.4      106       35.81    19900        3.38    67247.08  127.0.0.1:20001
 ------------------------------------------------------------------------------------------------------------------
```

**Comment by dbakewel** [comment]
I released the changes into the master branch so you don't need to use the Fair Start Position branch any more. See https://github.com/dbakewel/netbots/blob/master/CHANGELOG.md

**Comment by MCSnapTurtle** [comment]
Thanks, the server runs very well now.
