### ISSUE TITLE
netbots_ipc allows robot names to be any length.

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#35]
**Describe the bug**
netbots_ipc allows robot names to be any length. This causes a minor problem because the scoreboard and viewer both try to display the full name. This can cause display issues. More serious, someone could cause robot or server crashes (no specific case yet).

From netbots_ipc:
```
MsgDef = {
    # msg type              other required msg fields
    'joinRequest': {'name': 'str'},
```

**To Reproduce**
Create a robot with a long name, such as "abcdefghijklmnopqustuvwxyz1234567890" and then run a game with it.

**Expected behavior**
netbots_ipc should limit the maximum length of a robot name in the joinReuqest message. netbots_ipc should give an invalid message error is a robot submits a message with a name that is too long.

The server and viewer should both support the the maximum possible length defined in netbots_ipc.

**Console Output**
```
                    ---- Score -----  ------ Wins -------  --------- CanonFired ----------
              Name      Points     %    Count   AvgHealth    Count   AvgDamage   TotDamage  IP:Port
 ------------------------------------------------------------------------------------------------------------------
     WallBanger v1           0   0.0        0        0.00        0        0.00        0.00  127.0.0.1:20005
          Train v1           0   0.0        0        0.00        0        0.00        0.00  127.0.0.1:20004
   HideInCorner v1           0   0.0        0        0.00        0        0.00        0.00  127.0.0.1:20002
  abcdefghijklmnopqustuvwxyz1234567890           0   0.0        0        0.00        0        0.00        0.00  127.0.0.1:20003
 ------------------------------------------------------------------------------------------------------------------
```

![image](https://user-images.githubusercontent.com/11411338/57325313-9e184a80-70be-11e9-8038-c39425622f44.png)

**Work Around**
none.

**Comment by dbakewel** [comment]
Pull request https://github.com/dbakewel/netbots/pull/42 does not address a serious issue. Yes, it does make the server reject a long robot name but only after it has already been transmitted over the network to the server. Please see above where it says:

> netbots_ipc should limit the maximum length of a robot name in the joinReuqest message. netbots_ipc should give an invalid message error is a robot submits a message with a name that is too long.

So the fix should be in the protocol, not the server code itself. I suggest three changes to fix this problem:
1. The netbots_ipc MsgDef needs to change ```'joinRequest': {'name': 'str'}``` to something where the string type has a max length. Perhaps something like ```'joinRequest': {'name': ['str',1,16]}``` where the 1 and 16 are min and max length.
2. The netbots_ipc.isValidMsg() function must enforce string length min and max.
3. The README.md must be updated as needed.

**Comment by MCSnapTurtle** [comment]
Ok, I'll work on a better solution to this.

**Comment by dbakewel** [comment]
Also, the work of restricting string length in messages through validateMsg() will not be a one off. https://github.com/dbakewel/netbots/issues/39#issuecomment-492387057 would need to use it as well since 'class' would be a new string that robots could send. 'class' would also need a max length.

**Comment by dbakewel** [comment]
@MCSnapTurtle is assigned.

**Comment by dbakewel** [comment]
Fixed in https://github.com/dbakewel/netbots/pull/49
