### ISSUE TITLE
Different types of robots can be chosen

### ISSUE THREAD

**Issue by lsh010815** [dbakewel/netbots#39]
**Is your feature request related to a problem? Please describe.**
The programmers can choose different types of robots in order to make different tactics for their robots.

**Describe the solution you'd like**
Different types of robots can have different health and max speed. The higher health robots may have lower movement speed.

**Describe alternatives you've considered**
Also we can change other things for different types for robots such as turning rate, max request per step, acceleration rate, etc.

**Additional context**
It is hard to balance each kinds of robots, and I am not sure how to let the robots tell server what kind robots they want to be.

**Comment by dbakewel** [comment]
Are you thinking about a skills point system or something? For example each robot gets 10 points and can assign 4 speed and 6 health?

**Comment by mcstoer** [comment]
What about instead of adding health to robots, give them a percentage damage reduction.  Damage reduction would act as effectively more health, but would allow all robots' winning health to be compared.

**Comment by MCSnapTurtle** [comment]
I agree with mcstoer. Another thing like Increasing/decreasing shell speed may be a bad idea, as the damage per shot or shots fired will not indicate a superior bot, but may indicate a bot that has faster shell speed. So comparing post game stats for these may not be as helpful as before the changes.

**Comment by lsh010815** [comment]
Not the skills point system, but like the "classes" system. Skills point system will make some robots really over power. For example, if a robot has 1 health and 9 speed, none will hit it if it just do the "train" movement all the time. What I am thinking is we make some fixed classes let the programmers choose which one they want to be.

**Comment by dbakewel** [comment]
Okay, I class system sounds really neat. We want to make sure that the way robots are today is the default class. Why don't you make some concrete proposals of what other classes could be? I think one that slower but has more shielding would be good. One that's faster but has less shielding. One that could turn faster potentially (not sure on that one). Those are just ideas. Feel free to come up with your own.

**Comment by lsh010815** [comment]
Now the server does not allow robots change the max speed, acceleration rate, and turn rate, because the server just set the same value for all bots. What I'm thinking is remove those value form conf, and move them to botTemplate. Then create a new request let robots set which classes they want to be after they joined the game, and set the values base on what classes the bots chose. If a bot does not call the setType request, it will just be the default class. I'm not sure will this work, but I am working on the set type request.

**Comment by dbakewel** [comment]
OK, I like this but in a slightly different way. Here is a set of possible implementation notes. What do you think?

1. Allow the joinRequest message to **optionally** contain a class. It needs to be optional to be backwards compatible.

2. There would be a robot class called "default" which all robots would be assigned if they do not provide a class in joinRequest.

3. The server will ignore joinRequest classes unless the server is started with the -allowclasses option.

4. joinRequest could look like this:
Format: ```{ 'type': 'joinRequest', 'name': str, 'class': str}```
Example: ```{ 'type': 'joinRequest', 'name': 'Super Robot V3', 'class': 'default' } ```

5. I don't want to remove max speed, acceleration rate, and turn rate from the server conf. Rather the server conf should include a dictionary that is keyed by class string that contains the values for each class. Then the botTemplate only needs the class string. For example:
```
'conf' = {
        ...
        ...
        ...
        'classes': {
              'default': {
                   # Speeds and Rates of Change
                   'botMaxSpeed': 5,  # bots distance traveled per step at 100% speed
                   'botAccRate': 2.0,  # Amount in % bot can accelerate (or decelerate) per step
                   'botMinTurnRate': math.pi / 6000,  # Amount bot can rotate per turn in radians at 100% speed
                   'botMaxTurnRate': math.pi / 50,  # Amount bot can rotate per turn in radians at 0% speed
                 }
        }
        ...
        ...
        ...
    }


    botTemplate = {
        'name': "template",
        'class': 'default',
        ....
        ....
        ....
        }
```

**Comment by dbakewel** [comment]
@lsh010815 let me know if you want to implement this. I think it might be very cool.

**Comment by lsh010815** [comment]
Ok, I will work on both of them, but I have some questions about this issue. First, what will `msg['class']` be when you only sent robot name to server, will it be a empty string or default, or `msg['class']` just does not exist. Second, how do server know which classes the robot is when the server is doing the calculation. Third,  how to `parser.add_argument` the classes.

**Comment by dbakewel** [comment]
@lsh010815 is assigned.

**Comment by lsh010815** [comment]
After I changed the join request to `'joinRequest': {'name': 'str', 'class': 'str'}`, the bots have to send server the class message. So how to let the join request message optionally contain a class.

**Comment by dbakewel** [comment]
Ah! you don't need to change the definition of the joinRequest message since 'class' is **optional**. Robots can just add 'class' if they want to. netbots_ipc does not care if extra data is sent in a message. netbots_ipc will leave it along and pass is onto the server. Does that make sense?

**Comment by dbakewel** [comment]
Implemented on develop branch in https://github.com/dbakewel/netbots/commit/6498a4eb5a3b2834de960038a4324e890f250a7f
