### ISSUE TITLE
Moving Obstacles and Other Zones

### ISSUE THREAD

**Issue by jtaevans** [dbakewel/netbots#40]
**Is your feature request related to a problem? Please describe.**
The base game will become too simple as robots become more and more powerful.

**Describe the solution you'd like**
Obstacles and zones could slowly move during game play. Provisions might have to be made so that robots could know the new locations of obstacles.

**Describe alternatives you've considered**
It is possible that zones or obstacles could also expand or contract.

**Comment by dbakewel** [comment]
Yes, I think provisions would have to be made for the robot to understand what is happening with the obstacles in zones. Did you have any suggestions for this.

**Comment by jtaevans** [comment]
I think that the information could be delivered as part of a 'getInfoRequest' or as part of a separate new request to the server. 

To make the game even more challenging, it could be designed such that obstacles could only be detected by scanning.

**Comment by dbakewel** [comment]
I like that this would give a better reason to use getInfoRequest. Currently I never even used that request type in my better robots.

**Comment by dbakewel** [comment]
With the current server code structure, having obstacles and other zones move would be a huge change. For now, I'm going mark this as will not implement. If the code is restructured in the future then we can reconsider this sort of idea.
