### ISSUE TITLE
Team Mode

### ISSUE THREAD

**Issue by mcstoer** [dbakewel/netbots#46]
**Is your feature request related to a problem? Please describe.**
Currently the only mode that bots can have tournaments in is a free for all mode.  An introduction of new modes would allow for more diverse game play.

**Describe the solution you'd like**
There should be a mode the server puts bots on teams and informs the bots which team they are on.  netbots_srvmsghl.scanRequest() should return what team the enemy bot is on or ignore bots of the same team.  Bots should also be assigned similar colours so viewers can display the different teams.  This could be done with #24.  The server should also print out bot stats where each team member is compared to another bot in the same team instead of comparing all bots regardless of their team.  Scoring should be based on which team is left surviving at the end of a game.

**Describe alternatives you've considered**
With #39, there could be a mode where one bot is given boosted abilities and is faced against many bots.  There would be two teams, one consisting of the boosted bot and the other having all the remaining bots.

**Additional context**
With the introduction of teams, there could be an introduction of scoring objectives or other ways to get points instead of survival.

**Comment by MCSnapTurtle** [comment]
@mcstoer An idea for an objective could be some sort of capture zone where by being in the zone, the team earns points, sorta like king of the hill/ capture the flag. Instead of getting points for kills, they could get points purely from capture points. These game modes work much better for team mode, so there's no point adding them to FFA mode.

**Comment by dbakewel** [comment]
So I've been giving this some deep thought. 

I don't want to implement anything to help robots work together on teams. Robots can do that themselves now either by writing one program that controls more than one bot or by having two bots that send messages to reach other. they can use that mechanism to make sure they are not scanning or shooting a friendly robot.

Regarding team points and colors, that is a great idea. I suggest that when robots send a joinRequest they could include a 'team' field. Then the server could add a team scoreboard. No server options would be needed. The server would simply produce the team scoreboard if any robots identified as being on teams. If a bot does not provide the 'team' field then they simply are not on a team. The viewer would get that information as well, and can display teams at however it wants.

I think the class field and display would be step one. Special team scoring objectives would come later.


Thoughts?

**Comment by dbakewel** [comment]
With respect to adding an optional field to a message, see the following comment: https://github.com/dbakewel/netbots/issues/39#issuecomment-493315651
