### ISSUE TITLE
Random Colour implementation

### ISSUE THREAD

**Issue by JamesDarby345** [dbakewel/netbots#48]
**Is your feature request related to a problem? Please describe.**
add a server argument to randomize the bot colors so they are not always the same if you want

**Describe the solution you'd like**
put in a server arg in rundemo.bat, and have the colours randomize

**Describe alternatives you've considered**
none

**Additional context**
I have already coded this

**Comment by dbakewel** [comment]
Please see feedback I gave in pull request. :)

**Comment by JamesDarby345** [comment]
I will improve this feature and submit new pull request
