### ISSUE TITLE
Team Robot Demo

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#62]
I've added a team robot demo (https://github.com/dbakewel/netbots/commit/7309e54c8d36052ddb1aa32210f4cc3154032105) to the [master branch](https://github.com/dbakewel/netbots.git).

The demo uses python objects and the threading module to run two robots, each using it's own socket, at the same time, all in one program. 

**Please run "teamdemo.bat" and understand as much of "robots/team.py" as you can by Wednesday.**

Feel free to ask questions in the comments below.

**Comment by MCSnapTurtle** [comment]
How does the self.stop work? Where/how does it get changed from True to False?

**Comment by dbakewel** [comment]
Good question @MCSnapTurtle. That all comes down to the line 185: ```signal.signal(signal.SIGINT, quit)``` and the quit() function.

The signal call tells the operating system that if Ctrl-C is pressed then pause whatever is happening and run the quit() function. In other demo robots the quit() function called exit() which forced python to terminate the entire process. What we do in team.py is a little differnt.

In team.py the main() starts two more treads: leader and follower. After that main, leader, and follower are all running at the same time BUT these are threads, not processes. Unlike processes, threads share the same memory. So when the user presses Ctrl-C, the main thread pauses and calls quit(). The quit() function changes the value of leader.stop and follower.stop to True. When the quit() function is done everything else keeps running.

The next time leader and follower finish their loop they see that self.stop has changed value and the run() function will end and that will stop those threads. Once the threads have stopped then the isAlive() call will return False and the main will print stats and exit.

Does that help explain?

**Comment by dbakewel** [comment]
Also, these might be handy things to know:
- All objects in python are pass-by-object-reference so if you pass an object to a function it is not a copy of the object but a reference to the same object (same memory). [details](https://robertheaton.com/2014/02/09/pythons-pass-by-object-reference-as-explained-by-philip-k-dick/)
- In python, all object variables are public so if you have a reference to an object you can change everything inside it.

What this means is that in Follower self.stop is the same variable as follower.stop in quit(). Same for Leader.

**Comment by MCSnapTurtle** [comment]
Thanks!
