### ISSUE TITLE
Advanced Collisions does not consider speed altered by classes

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#65]
**Describe the bug**
Advanced Collisions still doesn't properly accommodate for classes that go faster or slower than the default speed. It currently still uses % speed which doesn't make any sense for classes that have higher or lower max speeds.

**To Reproduce**
Create a class that is much fast and then run it into a wall, obstacle or other robot. The increased speed will not create more damage.

**Expected behavior**
To be discussed but in general a bot going faster should suffer more damage from a collision. 

**Console Output**
n/a

**Work Around**
none

**Comment by dbakewel** [comment]
Note, this code is only on the develop branch right now.

**Comment by mcstoer** [comment]
See #64, it has a fix for that.

**Comment by dbakewel** [comment]
Proposed solution is in https://github.com/mcstoer/netbots/tree/advanced-collisions-merger-classes

**Comment by mcstoer** [comment]
If you want to keep hitSeverity closer to what it is now, https://github.com/mcstoer/netbots/tree/advanced-collisions has the solution.

#64 just uses that solution.

**Comment by dbakewel** [comment]
OK, Thanks. I'll look at that.

**Comment by dbakewel** [comment]
Fix applied in https://github.com/dbakewel/netbots/commit/bc9ad400ca3a1a80561a83c44270d2dd3dc47de2 from code in https://github.com/mcstoer/netbots/tree/advanced-collisions

This has not been tested in any real way yet.

**Comment by dbakewel** [comment]
@mcstoer the solution you proposed (eg. see below) does not need classes to be multipliers and works with classes being values or multipliers. It does the extra work itself and does not need to understand how classes are implemented. That kind of code will be less fragile and lead to fewer bugs in the future. I like it!

```
hitSeverity = bot['currentSpeed'] / 100.0 * d.getClassValue('botMaxSpeed', bot['class']) / \
                              d.conf['botMaxSpeed'] * math.cos(min(math.pi / 2, abs(bot['currentDirection'] - \
                              math.pi)))
```
