### ISSUE TITLE
Angles are not Normalized

### ISSUE THREAD

**Issue by mcstoer** [dbakewel/netbots#8]
**Describe the bug**
If a robot sends a direction request that is less than 0 or greater than 2pi it does not normalize the angle and throws an error.

**To Reproduce**
Make a robot shot a shot outside of the range between 0 and 2pi.

**Expected behavior**
The server should use the normalizeAngle function in netbots_math and normalize the angle.

**Console Output**
Include error and several lines leading up to the error. Consider including verbose or debug output.

ERROR 2019-04-25 18:58:46.243 netbots_ipc.isValidMsg(): Msg 'direction' key has a value 37.69911184307752 which is out of range [0,6.283185307179586] : {'type': 'fireCanonRequest', 'direction': 37.69911184307752, 'distance': 648.8526396756706, 'msgID': 21559}

**Work Around**
Is there a way to work around the problem?
The only work around is to make your robot normalize the angles before sending them to the server.

**Comment by dbakewel** [comment]
This not a bug but rather the design of the NetBots protocol. 

**What is going on?** The error is **not** coming from the server. If you run your robot with "-debug" you will see that the message that produces the error is never sent to the server. The netbots_ipc module, used by the robot, enforces the protocol including the message definition for [fireCanonRequest](https://github.com/dbakewel/netbots#fireCanon). The netbots_ipc module will not send or receive any message that does not match this definition, rather it will return an error or raise an exception depending which method is being used.

**Why is it like this?** There are many reasons to restrict the protocol to a small range of values. The most critical is reducing the need for error checking at all levels of the code. If the server knows that all angles are in the range 0 <= angle <= 2pi then it never needs to normalize any angles. Clearly defining where the work of nomalizing angles must be done means other parts of the code can assume it is correct. The netbots_ipc protects the code using it by ensuring only good values can be sent or received.

**How to fix?** The simplest way is to normalize all angels in your code before they are included in a message. If this looks messy in your code then you could write helper functions that generate each message type and normalize angles as needed. A **better solution** would be to subclass the NetBotSocket module and have it inspect all message fields and compare that to the message definition. Where it finds a message definition of 0 to 2pi, have it normalize the angle being passed. As discussed this change would only be on the robot and if the sub-classed NetBotSocket somehow sent a bad value then the server would still reject the message.

**Comment by dbakewel** [comment]
The error is from the robot netbots_ipc line 83:

```
                    if msg[fld] < fldspec[1] or msg[fld] > fldspec[2]:
                        log("Msg '" + fld + "' key has a value "+str(msg[fld])+" which is out of range ["+str(fldspec[1])+","+str(fldspec[2])+"] : " + str(msg), "ERROR")
                        return False
```

**Comment by dbakewel** [comment]
I was also thinking about this in terms of accuracy. If an angle is represented in a very large non normalized way, then running it through normalizeAngle() may reduce its floating point accuracy. It is best to manage your angles so they do not need to be normalized or at least normalized in only one rotation. This concern may be academic however.
