### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#89]
Before release of NetBots 2.0 the following doc updates need to happen:

@mcstoer - After https://github.com/dbakewel/netbots/issues/68, add a line about speed and angle effecting collisions to https://github.com/dbakewel/netbots/blob/master/README.md#damage 

@MCSnapTurtle - After https://github.com/dbakewel/netbots/issues/77 update all references to train in readme.

@JamesDarby345 , @mcstoer - update images in readme.

@jtaevans - Add a sentence or two about instant replay to viewer help message (use argparse epilog="text")

@lsh010815 - Add a new doc about robot classes in docs/classes.mb (Optional)

@dbakewel :
 - docs/aritecture.md (Optional)
 - Add team robot to readme
 - updated server config in readme
 - updated serer commandline help in readme (after 
 - https://github.com/dbakewel/netbots/issues/68)

**Comment by mcstoer** [comment]
The scanning image in the README is still the older image.  Is this intentional?
