### ISSUE TITLE
Robots for Github readme video

### ISSUE THREAD

**Issue by dbakewel** [dbakewel/netbots#90]
Hi @lsh010815 @JamesDarby345 @jtaevans @mcstoer @MCSnapTurtle ,

I'd like to make a 30 second video that demos NetBots for the GitHub README.md. I don't want to use the demo robots because they are so basic. Would any of you be interested in having your robots in a short video? Robot source code would not be exposed.

If you are interested then please let me know I have your permission in the comments below. 

Thanks
@dbakewel

**Comment by mcstoer** [comment]
I would be fine with you using my current robot, I have a newer one you can use.

**Comment by jtaevans** [comment]
You're welcome to use any of mine as well.

**Comment by MCSnapTurtle** [comment]
You can use any of mine, but hanazuki v4 is probably better than Yamato v8 to use because hanazuku has unique wall avoiding movement.
